Fix For React Navigation Beta 20+
timomeh/react-native-material-bottom-navigation pull request #62
Opened 2017-12-06 00:32 UTC by keeleycarrigan

This seems to fix the [issue](https://github.com/timomeh/react-native-material-bottom-navigation/issues/61) people are having with React Navigation Beta.20+. Just need to pass in `previousScene`.

2017-12-06 08:05 UTC, timomeh commented
Thank you very much! I'll check this out at the weekend

2017-12-14 20:07 UTC, timomeh requested changes
Thank you very much for your PR! I tested it and it works. If you can remove that one semicolon, I'm going to merge it and release a new version.

Sorry for being picky about a semicolon, but I want to keep a consistent style throughout the code.

2017-12-14 20:07 UTC, timomeh commented on lib/NavigationComponent.js
> +    const previousScene = navigationState.routes[navigationState.index];
Please remove semicolon

2017-12-14 23:08 UTC, keeleycarrigan commented
@timomeh sorry man, should have caught that. I am equally as picky in my own code reviews.

2017-12-15 07:23 UTC, timomeh approved these changes

2017-12-15 07:23 UTC, merged

2017-12-15 07:25 UTC, timomeh commented
Will release it soon